#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo 'ESLint Check Failed. Run npm run lint:fix.';
        false; 
)

npm run build ||
(
    echo 'Next build failed.'
    false;
)
